### ISSUE TITLE
create Ros2BaseNode without LifeCycle functionalities

### ISSUE THREAD

**Issue by Svastits** [kroshu/kroshu_ros2_core#1]
Node and LifeCycleNode does not have a common base, declare_parameter method is defined in both, but both have a rclcpp::node_interfaces::NodeParametersInterface
 -> to avoid code duplication, proposed structure:

class ParameterHandler(rclcpp::node_interfaces::NodeParametersInterface paramIF)
  + std::shared_ptr<rclcpp::node_interfaces::NodeParametersInterface> paramIF_
  + std::vector<std::shared_ptr<ParameterBase>> params_
  + void registerParameter(std::shared_ptr<ParameterBase> param_shared_ptr)
  + rcl_interfaces::msg::SetParametersResult onParamChange(const std::vector<rclcpp::Parameter> & parameters)
  + bool canSetParameter(const ParameterBase & param)

class ROS2BaseNode: public rclcpp::Node
  + ParameterHandler (created in contructor with argument this->get_node_parameters_interface()

class ROS2BaseNode: public rclcpp_lifecycle::LifecycleNode
  + ParameterHandler (created in contructor with argument this->get_node_parameters_interface()
  + on_configure(),  on_cleanup(), etc.

**Comment by resizoltan** [comment]
Good idea!

Side note: at some point in the future we should consider making the ParamHandler real-time safe, because the current shared pointer approach uses dynamic memory allocation. We can maybe use the TLSF allocator, but I think it's easier and completely fine to allocate the memory statically.

**Comment by kovacsge11** [comment]
> Good idea!
> 
> Side note: at some point in the future we should consider making the ParamHandler real-time safe, because the current shared pointer approach uses dynamic memory allocation. We can maybe use the TLSF allocator, but I think it's easier and completely fine to allocate the memory statically.

Could you please create an issue for this?
